# Generated by Django 3.1 on 2021-02-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_id', models.IntegerField()),
                ('Appointment_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=255)),
                ('Appointment_start', models.TimeField()),
                ('Appointment_End', models.TextField()),
                ('Priority', models.IntegerField()),
            ],
            options={
                'db_table': 'Doctor_details',
            },
        ),
        migrations.CreateModel(
            name='Patients_appointment_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_id', models.IntegerField()),
                ('Patient_name', models.CharField(max_length=255)),
                ('Serious_illness', models.TextField()),
                ('Allergies', models.TextField()),
                ('Medical_history', models.TextField()),
                ('Appointment_start', models.TimeField()),
                ('Appointment_End', models.TextField()),
                ('Priority', models.IntegerField()),
            ],
            options={
                'db_table': 'Patient_Appointment_details',
            },
        ),
        migrations.DeleteModel(
            name='Patients_login',
        ),
    ]
